In [1]:
#importar as bibliotecas 
from numpy import pi
import numpy as np

In [2]:
print('Versão atual do numpy é', np.__version__)

Versão atual do numpy é 1.18.5


In [4]:
#Criação de array
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [5]:
#Mostrar o tipo de dado
a.dtype

dtype('int32')

In [6]:
#Mostrar o formato da minha matriz
a.shape

(3,)

In [7]:
#Criação de um outro tipo de array
b = np.array([1,23333, 3.5, 5.1])
b

array([1.0000e+00, 2.3333e+04, 3.5000e+00, 5.1000e+00])

In [8]:
#Mostrar o tipo de dado
b.dtype

dtype('float64')

In [9]:
#Criar array bidimensional 
c = np.array([(1.5, 2, 3), (4, 5, 6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
c.dtype

dtype('float64')

In [13]:
#Verificando dimensões de c
c.ndim

2

In [14]:
#Criar uma matriz de numeros complexos
d = np.array([[1, 2], [3, 4]], dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])